### ISSUE TITLE
SVG 版本 toFront 不生效

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/g#442] opened 2020-03-12 05:17 UTC
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/5538e2b2](https://riddle.alibaba-inc.com/riddles/5538e2b2)

### Steps to reproduce
最下面已经把第一个图形 toFront，然而并没有被放置到上层。使用 g-canvas 是可以的。

### What is expected?
SVG 图形 toFront 生效。

### What is actually happening?
SVG 图形 toFront 不生效。

| Environment | Info |
|---|---|
| g | 3.4.7 |
| System | Mac |
| Browser | Chrome |

**Comment by dengfuping** [comment] 2020-04-10 02:22
- Duplicate of #462.

**Closed by dengfuping** 2020-04-10 02:22 UTC
